/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    TheLogoCalendar: typeof import('./components/TheLogoCalendar.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheNFT: typeof import('./components/TheNFT.vue')['default']
    TypedText: typeof import('./components/TypedText.vue')['default']
    TypeWritter: typeof import('./components/TypeWritter.vue')['default']
  }
}
